// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDOIH8N1EMVjrAJePlm2ll2ntovVfkgfM',
    appId: '1:56010970512:web:ea429c935e997da9550f15',
    messagingSenderId: '56010970512',
    projectId: 'projetotime4',
    authDomain: 'projetotime4.firebaseapp.com',
    storageBucket: 'projetotime4.appspot.com',
    measurementId: 'G-JKGV4RVDZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvpCd8k30v-dy9hhNiuywCpqcr7IEsMdM',
    appId: '1:56010970512:android:5e8f38bbc836846d550f15',
    messagingSenderId: '56010970512',
    projectId: 'projetotime4',
    storageBucket: 'projetotime4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcVilpGEdD6V2ZQTKnhM3FUmED1fmuiHg',
    appId: '1:56010970512:ios:d81df667dba84236550f15',
    messagingSenderId: '56010970512',
    projectId: 'projetotime4',
    storageBucket: 'projetotime4.appspot.com',
    iosClientId: '56010970512-2g66vbbll5h38h9j22i6158r1jo8edto.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetotime04Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcVilpGEdD6V2ZQTKnhM3FUmED1fmuiHg',
    appId: '1:56010970512:ios:d81df667dba84236550f15',
    messagingSenderId: '56010970512',
    projectId: 'projetotime4',
    storageBucket: 'projetotime4.appspot.com',
    iosClientId: '56010970512-2g66vbbll5h38h9j22i6158r1jo8edto.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetotime04Flutter',
  );
}
